USE [master]
GO

/****** Object:  Database [QLdiemdaihocspktHungYen]    Script Date: 5/11/2023 2:40:02 PM ******/
CREATE DATABASE [QLdiemdaihocspktHungYen]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QLdiemdaihocspktHungYen', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLdiemdaihocspktHungYen.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QLdiemdaihocspktHungYen_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QLdiemdaihocspktHungYen_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QLdiemdaihocspktHungYen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET ARITHABORT OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET  ENABLE_BROKER 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET  MULTI_USER 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QLdiemdaihocspktHungYen] SET  READ_WRITE 
GO

